# Generated by Django 3.2.3 on 2021-05-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210519_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bride'),
        ),
        migrations.AlterField(
            model_name='event',
            name='groom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.groom'),
        ),
    ]
